### ISSUE TITLE
create-react-app下使用，正则替换文件路径错误

### ISSUE THREAD

**Issue by zcmk123** [AngusFu/webpack4-cdn-plugin#44]
不清楚是不是webpack的版本或loader、plugin导致的最终生成的source有些不一样

这个是create-react-app生成的source 左右两边带括号
![_8E0_JSWI3P 1TB5`C3_}6O](https://user-images.githubusercontent.com/20919760/134800222-d494d11a-2953-4c66-90a4-06d4500a1c2c.png)

这个是vue-cli生成的source 左右两边没有括号
![image](https://user-images.githubusercontent.com/20919760/134800266-5c180164-6117-4844-8eee-c53aba185e5d.png)

在走replacePublicPath这里面的逻辑时
这个正则 /__webpack_require__\.p\s*\+\s*([^;\n]*?)[;\n]/g;
把带有括号的source匹配出的结果有错误，多匹配了一个括号进去
![image](https://user-images.githubusercontent.com/20919760/134800393-1d39a38a-90d5-4ea5-9e1e-e43d5f9ef0da.png)

**Comment by zcmk123** [comment]
请问还有在维护这个插件吗。。。。或者我可以提pr修复吗 @AngusFu

**Comment by AngusFu** [comment]
@zcmk123 不好意思  之前可能消息太多读漏掉了  o(╯□╰)o  因为工作变动，这个插件现在我没有太多使用场景了。如果你有兴趣，可以提 pr 修复哈。

**Comment by AngusFu** [comment]
可参考 https://github.com/AngusFu/webpack5-cdn-plugin/commit/30853f0df98b55a360998f1a86cdc5d14a06c94d 修复
